mavAgenda/landing/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'landing'
urlpatterns = [
    path('', views.login, name='login'),
    path('selectcourses/<int:pk>', views.selectcourses, name='selectcourses'),
    path('schedule/<int:pk>', views.schedule, name='schedule'),
    path('createuser/', views.createuser, name='createuser'),
]

mavAgenda/mavAgenda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('landing/', include('landing.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mavAgenda/landing/models.py
from django.db import models
from django.contrib.auth.models import User

#class User(models.Model):
    #userPK = models.IntegerField()
    #username = models.CharField(max_length=75)
    #password = models.CharField(max_length=75)

class Degree(models.Model):
    BS = 'Bachelor of Science'
    MS = 'Master of Science'
    PhDS = 'Doctor of Science'
    DIPLOMA_CHOICE = (
        (BS, 'Bachelor of Science'),
        (MS, 'Master of Science'),
        (PhDS, 'Doctor of Science'),
    )
    degree_diploma = models.CharField( max_length=50, choices=DIPLOMA_CHOICE, default=BS)
    MAJ = 'Major'
    MIN = 'Minor'
    CON = 'Concentration'
    TYPE_CHOICE = (
        (MAJ, 'Major'),
        (MIN, 'Minor'),
        (CON, 'Concentration'),
    )
    degree_type = models.CharField( max_length=50, choices=TYPE_CHOICE, default=MAJ )
    CSCI = 'Computer Science'
    MIS = 'Management Information Systems'
    BIOI = 'Bioinformatics'
    ITIN = 'IT Innovation'
    CYBR = 'Cybersecurity'
    TRACK_CHOICE = (
        (CSCI, 'Computer Science'),
        (MIS, 'Management Information Systems'),
        (BIOI, 'Bioinformatics'),
        (ITIN, 'IT Innovation'),
        (CYBR, 'Cybersecurity'),
    )
    degree_track = models.CharField( max_length=50, choices=TRACK_CHOICE, default=CSCI )
    degree_users = models.ManyToManyField(User)

class Requirement(models.Model):
    #req_pk = models.IntegerField()
    req_name = models.CharField(max_length=50)
    req_credits = models.IntegerField()
    req_degrees = models.ManyToManyField(Degree)

class Course(models.Model):
    #course_pk = models.IntegerField()
    course_name = models.CharField(max_length=75)
    course_num = models.CharField(max_length=15)
    A = "All"
    S = "Spring"
    F = "Fall"
    M = "Summer"
    SEM_CHOICE = (
        (A, "All"),
        (S, "Spring"),
        (F, "Fall"),
        (M, "Summer"),
    )
    course_semester = models.CharField(max_length=10, choices=SEM_CHOICE, default=A)
    course_credits = models.IntegerField()
    N = "No"
    Y = "Lab"
    W = "Waiver"
    SPECIAL_TYPE_CHOICE = (
        (N, "No"),
        (Y, "Lab"),
        (W, "Waiver"),
    )
    course_special = models.CharField(max_length=15, choices=SPECIAL_TYPE_CHOICE, default=N)
    course_comment = models.CharField(max_length=200, blank=True)
    course_requirements = models.ForeignKey(Requirement, on_delete=models.CASCADE)

class Prereq(models.Model):
    #prereq_pk = models.IntegerField
    C = "Corequisite"
    P = "Prerequisite"
    REQ_CHOICE = (
        (C, "Corequisite"),
        (P, "Prerequisite"),
    )
    prereq_type = models.CharField(max_length=20, choices=REQ_CHOICE, null=True)
    prereq_courses = models.ManyToManyField(Course)

class Complete(models.Model):
    complete_user = models.ForeignKey(User, on_delete=models.CASCADE)
    complete_courses = models.ManyToManyField(Course)

class UserPreferences(models.Model):
    pref_minCredits = models.IntegerField()
    pref_maxCredits = models.IntegerField()
    pref_summer = models.BooleanField()
    pref_summerMinCredits = models.IntegerField()
    pref_summerMaxCredits = models.IntegerField()
    pref_user = models.ForeignKey(User, on_delete=models.CASCADE)

#class UserDegree(models.Model):
    #user_pk = models.ForeignKey(User, primary_key=True, on_delete=models.CASCADE)
    #degree_pk = models.ForeignKey(Degree, on_delete=models.CASCADE)

#class DegreeReq(models.Model):
    #degree_pk = models.ForeignKey(Degree, primary_key=True,on_delete=models.CASCADE)
    #requirement_pk = models.ForeignKey(Requirement, primary_key=True, on_delete=models.CASCADE)

#class RequirementCourse(models.Model):
    #requirement_pk=models.ForeignKey(Requirement, primary_key=True, on_delete=models.CASCADE)
    #course_pk=models.ForeignKey(Course, primary_key=True, on_delete=models.CASCADE)

#class CoursePreqreq(models.Model):
    #course_pk=models.ForeignKey(Course, primary_key=True, on_delete=models.CASCADE)
    #prereq_pk=models.ForeignKey(Prereq, primary_key=True, on_delete=models.CASCADE)

#class PrereqCourse(models.Model):
    #prereq_pk = models.ForeignKey(Prereq, primary_key=True, on_delete=models.CASCADE)
    #course_pk = models.ForeignKEey(Course, preimary_key=True, on_delete=models.CASCADE)

mavAgenda/landing/forms.py
from django import forms
from .models import *


'''
@EmailForm collection of fields to allow for user login with email address
@forms.Form: associated data within fields
'''
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','password',)

'''
@DegreeForm collection of fields to allow for user to specifiy degree
@forms.Form: associated data within fields
'''
#class DegreeForm(forms.ModelForm):
    #class Meta:
        #model = Degree
        #fields = ('degree',)

'''
@UserForm collection of fields to track user's completed courses
@forms.Form: associated data within fields
'''
#class UserCompletedForm(forms.ModelForm):
    #class Meta:
        #model = Complete
        #fields = ('user', 'complete')

mavAgenda/landing/templates/forms.py
from django import forms


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

mavAgenda/landing/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .forms import *
from .models import *
from django.contrib.auth.models import User

from datetime import datetime

'''
@getUserByEmail searches the User table to find the User object with a corresponding email
@param e: the email being searched for
'''
def getUserByEmail(e):
    userTable = User.objects.all()
    for cu in userTable:
        if cu.username == e:
            return cu

'''
@getDegree searches the Degree table to find the Degree object with corresponding degree and major
@param d: degree attribute of Degree being searched for
@param m: major attribute of Degree being searched for
'''
def getDegree(diploma, type, track):
    degreeTable = Degree.objects.all()
    for deg in degreeTable:
        if deg.degree_diploma == diploma and deg.degree_type == type and deg.degree_track == track:
            return deg

'''
@getCompletedByUser provides a list of Course (objects) the user has taken
@param uID: the primary key corresponding to the active user
'''
def getCompletedByUser(uID):
    cu = User.objects.get(pk=uID)
    completedCourses = []
    for cc in Complete.objects.get(user=cu).complete.all():
        completedCourses.append(cc)
    return completedCourses

'''
@getCoursesForUser provides a list of Course (objects) the user must complete for their respective Degree
@param uID: the primary key corresponding to the active user
'''
def getCoursesForUser(uID):
    requiredCourses = []
    reqs = Degree.objects.get(user=uID).req.all()
    for r in reqs:
        catalog = r.course.all()
        for g in catalog:
            requiredCourses.append(g)
            prereqs = Course.objects.get(id=g.id).prereqs.all()
            for pr in prereqs:
                additionalCourse = Course.objects.get(id=pr.prereq.id)
                if additionalCourse not in requiredCourses:
                    requiredCourses.append(additionalCourse)
    return requiredCourses

'''
@removeCoursesTaken provides a list of Course (objects) the user must still take (required, but not completed classes)
@param requiredClasses: a list of Course (objects) required for the User's Degree
@param classesTaken: a list of Course (objects) that the User has already completed
'''
def removeCoursesTaken( requiredClasses, classesTaken ):
    validCourses = []
    for rc in requiredClasses:
        if rc not in classesTaken :
            validCourses.append(rc)
    return validCourses

'''
@checkPrereqsMet determines if the User has met all Prereqs for a particular Course
@param prereqs: a list of Course (objects) corresponding to Prereqs for a given Course
@param classesTaken: a list of Course (objects) that the User has already completed
@parm scheduledClasses: a list of Course (objects) the scheduling algorithm has accounted for already
'''
def checkPrereqsMet(preqreqs, classesTaken, currentSemester):
    met = True
    for pr in preqreqs:
        notInClassesTaken = pr.prereq not in classesTaken and pr.this_or not in classesTaken
        inCurrentSemester = pr.prereq in currentSemester or pr.this_or in currentSemester
        if notInClassesTaken:
            met = False
            break
        elif inCurrentSemester:
            met = False
            break
    return met

'''
@checkOfferedSemester determines if a given Course if offered during the current semester
@param course: the Course under test
@param ssf: the Spring, Summer, Fall, offering attribute of the Course
'''
def checkOfferedSemester(course, ssf):
    offered = False
    if course.semester == ssf or course.semester == 'All':
        offered = True
    return offered

'''
@checkCourseValid determines if a given Course can be taken during a given semester
@param course: the Course under test
@param classesTaken: a list of Course (objects) that the User has already completed
@parm scheduledClasses: a list of Course (objects) the scheduling algorithm has accounted for already
@param ssf: the Spring, Summer, Fall, offering attribute of the Course
'''
def checkCourseValid(course, classesTaken, semesterCourses, ssf): #checkCourseValid( nc, classesTaken, semesterCourses, ssfSemester )
    valid = False
    prereqs = course.prereqs.all()
    prereqsMet = checkPrereqsMet(prereqs, classesTaken, semesterCourses)
    offered = checkOfferedSemester(course, ssf)
    if prereqsMet and offered:
        valid = True
    return valid

'''
@getSemesterByMonthYear determines semester (Spring, Summer, Fall) according to current month
@param m: current month
'''
def getSemesterByMonthYear( m ):
    if  m < 5 :
        title = "Spring"
    elif  m < 8 :
        title = "Summer"
    else:
        title = "Fall"
    return title

'''
@generateNewSemester creates a new logical semester
@param semester: previous semester list
'''
def generateNewSemester(semester):
    ssf = semester[0]
    nextSemester = ""
    y = semester[1]
    if ssf == "Spring" :
        nextSemester = "Summer"
    elif ssf == "Summer" :
        nextSemester = "Fall"
    else:
        nextSemester ="Spring"
        y += 1
    semester[0] = nextSemester
    semester[1] = y
    semester[2] = []
    return semester

'''
@isFull determines if a semester has hit the maximum number of credits allowable
@param courseList: list of Course (objects) the user is scheduled to take during current semester
'''
def isFull(courseList):
    full = False
    totalCredits = 0
    for c in courseList:
        totalCredits+= c.credits
    if totalCredits >= 12 and totalCredits <= 16:
        full = True
    return full

'''
@createSchedule generates semester-by-semester schedule for User's needed Courses according to Degree
@param uID: primary key associated with active user
'''
def createSchedule(uID):
    loopCount = 0
    maxLoopCount = 35
    reqTracker = [] #used to track if Req credit quotas have been met
    requiredClasses = getCoursesForUser(uID)
    reqs = Degree.objects.get(user=uID).req.all()
    for r in reqs:
        req_id = r.id
        req_name = r.name
        req_type = r.req_type
        req_creds = r.credits
        req_start = 0
        reqTracker.append([req_id, req_name, req_type, req_creds, req_start])
    classesTaken = getCompletedByUser(uID)
    neededClasses = removeCoursesTaken( requiredClasses, classesTaken )
    schedule = []
    currentMonth = datetime.now().month
    currentYear = datetime.now().year
    ssfSemester = getSemesterByMonthYear(currentMonth)
    semester = [ssfSemester, currentYear, []]
    currentSemester = generateNewSemester(semester)
    scheduleComplete = True
    for c in classesTaken:
        for r in reqTracker:  # determine which Req this course falls under
            if c in Req.objects.get(id=r[0]).course.all():
                r[4] += c.credits  # increment the completed running total for that Req
    while neededClasses != [] and loopCount < maxLoopCount:
        loopCount+=1
        for nc in neededClasses:
            if ( checkCourseValid( nc, classesTaken, currentSemester[2], ssfSemester ) ):
                currentSemester[2].append(nc)
                classesTaken.append(nc)
                neededClasses.remove(nc)
                for r in reqTracker: # determine which Req this course falls under
                    if nc in Req.objects.get(id=r[0]).course.all():
                        r[4]+=nc.credits # increment the completed running total for that Req
            if ( neededClasses != [] and isFull(semester[2])):
                schedule.append(semester[:])
                semester = generateNewSemester(semester)
                break
            scheduleComplete = True
            for r in reqTracker:
                if r[3] > r[4]:
                    scheduleComplete = False
        if scheduleComplete:
            print( "BREAKING FREEEEEEE!!!!")
            break
    return schedule

'''
@generateCheckBoxEntities creates a list of tuples of requirements, course names and numbers for the selectcourses page
@param uID: primary key corresponding to the active user
'''
def generateCheckBoxEntities(uID):
    reqs = Degree.objects.get(user=uID).req.all()
    checkBoxEntities = []
    for r in reqs:
        req_id = r.id
        req_name = r.name
        req_type = r.req_type
        req_creds = r.credits
        catalog = r.course.all()
        courseList = []
        for g in catalog:
            number = g.num
            name = g.name
            creds = g.credits
            courseList.append([number,name,creds])
        checkBoxEntities.append([req_id, req_name, req_type, req_creds, courseList])
    return checkBoxEntities

'''
@generateMajorDD creates a list of possible majors for use on the createuser page
'''
def generateMajorDD():
    allDegrees = Degree.objects.all()
    majors = []
    for d in allDegrees:
        if d.degree_type == "MAJ" and d.degree_track not in majors:
            majors.append(d.degree_track)
    return majors

def generateMinorDD():
    allDegrees = Degree.objects.all()
    minors = []
    for d in allDegrees:
        if d.degree_type == "MIN" and d.degree_track not in minors:
            minors.append(d.degree_track)
    return minors

def generateConcentrationsDD():
    allDegrees = Degree.objects.all()
    concentrations = []
    for d in allDegrees:
        if d.degree_type == "CON" and d.degree_track not in concentrations:
            concentrations.append(d.degree_track)
    return concentrations

def generateDiplomaDD():
    allDegrees = Degree.objects.all()
    diplomas = []
    for d in allDegrees:
        if d.degree_diploma not in diplomas:
            diplomas.append(d.degree_diploma)
    return diplomas


mavAgenda/landing/templates/landing/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- fonts -->

    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:700" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:300,400,400i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:302,300i" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <!-- project stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'landing/css/style.css' %}" />
    <title>MavLink Made Easy</title>
</head>
<body>
<div>
    <a href="{% url 'landing:login' %}">
        <img src="{% static 'landing/img/MMElogo.JPG' %}" alt="Logo" width="190" height="170" style="margin-top: -10px"/>
    </a>
{% block content %}
{% endblock %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="icons">
        <a href="{% url 'landing:login' %}"><i class="fas fa-bars fa-x"></i></a>
    </div>
    <p align="right"><i>After PyParty 2018 | <a href="https://github.com/lkoperski/MavLinkMadeEasy">github</a></i></p>
</div>
</body>
</html>

mavAgenda/landing/templates/landing/createuser.html
{% extends 'landing/base.html' %}
{% block content %}

<script>
function removeInfo(divID) {
    var select = document.getElementById(divID);
    select.removeChild(select.lastChild);
    return false;
}
function notSelected( idBase, searchFor, num ) {
    var previousSelected  = false
    for ( var i =1; i<=num; i++ ){
        var id = idBase + i
        var select = document.getElementById(id);
        if ( select.value == searchFor ) {
            previousSelected = true;
            break;
        }
    }
    return !previousSelected;
}
function showSummerInfo() {
    document.getElementById("summer-info").style.display = "block";
}
function hideSummerInfo() {
    document.getElementById("summer-info").style.display = "none";
}
function showMajorInfo( diplomas, majors, num ) {
    var container = document.getElementById("major-info");
    var line = document.createElement("p");
    var dipHeader = document.createTextNode("Desired Diploma");
    var dip = document.createElement("select");
    var space = document.createElement("nbsp");
    dip.id = "id_d-diploma-" + (num+1);
    dip.name = "id_d-diploma-" + (num+1);
    for (i=0; i<diplomas.length; i++ ) {
            var dipChoice = document.createElement("option");
            dipChoice.value = diplomas[i];
            dipChoice.text = diplomas[i];
            dip.appendChild(dipChoice);
    }
    var majHeader = document.createTextNode("Major:");
    var maj = document.createElement("select");
    maj.id = "id_d-major-" + (num+1);
    maj.name = "id_d-major-" + (num+1);
    for (i=0; i<majors.length; i++ ) {
        if ( notSelected("id_d-major-", majors[i], num) ) {
            var majChoice = document.createElement("option");
            majChoice.value = majors[i];
            majChoice.text = majors[i];
            maj.appendChild(majChoice);
        }
    }
    var removeButton = document.createElement("button");
    removeButton.setAttribute( "onclick", "removeInfo('major-info')");
    removeButton.innerHTML = "Remove Major";
    line.appendChild(dipHeader);
    line.appendChild(dip);
    line.appendChild(space);
    line.appendChild(majHeader);
    line.appendChild(maj);
    line.appendChild(space);
    line.appendChild(removeButton)
    container.appendChild(line);
    return false;
}
function showMinorInfo(minors, num) {
    var container = document.getElementById("minor-info");
    var line = document.createElement("p");
    var minHeader = document.createTextNode("Desired Minor");
    var min = document.createElement("select");
    var space = document.createElement("nbsp");
    min.id = "id_d-minor-" + (num+1);
    min.name = "id_d-minor-" + (num+1);
    for (i=0; i<minors.length; i++ ) {
        if (notSelected("id_d-minor-", minors[i], num)) {
            var minChoice = document.createElement("option");
            minChoice.value = minors[i];
            minChoice.text = minors[i];
            min.appendChild(minChoice);
        }
    }
    var removeButton = document.createElement("button");
    removeButton.setAttribute( "onclick", "removeInfo('minor-info')");
    removeButton.innerHTML = "Remove Minor";
    line.appendChild(minHeader);
    line.appendChild(min);
    line.appendChild(space);
    line.appendChild(removeButton)
    container.appendChild(line);
    return false;
}
function showConcentrationInfo(concentrations, num) {
    var container = document.getElementById("concentration-info");
    var line = document.createElement("p");
    var conHeader = document.createTextNode("Desired Concentration");
    var con = document.createElement("select");
    var space = document.createElement("nbsp");
    con.id = "id_d-concentration-" + (num+1);
    con.name = "id_d-concentration-" + (num+1);
    for (i=0; i<concentrations.length; i++ ) {
        if (notSelected("id_d-concentration-", concentrations[i], num)) {
            var conChoice = document.createElement("option");
            conChoice.value = concentrations[i];
            conChoice.text = concentrations[i];
            con.appendChild(conChoice);
        }
    }
    var removeButton = document.createElement("button");
    removeButton.setAttribute( "onclick", "removeInfo('concentration-info')");
    removeButton.innerHTML = "Remove Concentration";
    line.appendChild(conHeader);
    line.appendChild(con);
    line.appendChild(space);
    line.appendChild(removeButton);
    container.appendChild(line);
    return false;
}
</script>

<form method="POST" class="email" id = "email">

    {% csrf_token %}
    <br>
    <div class="select" id="selectMajor">

        <h3>User information</h3>

        <p class="errormessage" id="errormessage">{{message}}</p>

        <p id="emailbox" name="emailbox" class="MAVselect">Email:<input id="email-input" name="email-input"
               minlength="1" required
               placeholder="Email" />
        </p>

        <p name ="password" class="MAVselect">Password: <input type="password" id="password-input" name="password-input"
               minlength="1" required
               placeholder="Password" />
        </p>

        <br><br>

        <h3>Select Your Major</h3>

        <div id="major-info" display="block">

            <p name="major-opts" class="MAVselect">
                Desired Diploma:
                <select name="id_d-diploma-1" id="id_d-diploma-1">
                    <option selected disabled>Choose here</option>
                    {% for d in diplomas %}
                        <option value="{{d}}">{{ d }}</option>
                    {% endfor %}
                </select>

                <nbsp></nbsp>
                Major:
                <!-- please leave this name and id as is... django backend related (see Lauren for questions) -->
                <select name="id_d-major-1" id="id_d-major-1">
                    <option selected disabled>Choose here</option>
                    {% for m in majors %}
                        <option value="{{m}}">{{ m }}</option>
                    {% endfor %}
                </select>
            </p>

        </div>

        <button type="button" name="add-major-button" class="MAVbutton" onclick="showMajorInfo( {{diplomas}}, {{majors}}, 1 )">add major</button>

        <br><br>

        <h3>Minors</h3>

        <div id="minor-info" display="block"></div>

        <button type="button" name="add-minor-button" onclick="showMinorInfo( {{minors}}, 0 )">add minor</button>

        <br><br>

        <h3>Concentrations</h3>

        <div id="concentration-info" display="block"></div>

        <button type="button" name="add-concentration-button" onclick="showConcentrationInfo( {{concentrations}}, 0 )">add concentration</button>

        <br><br>

        <h3>Preferences</h3>

        <p name ="fall-spring-credits" class="MAVselect">Please enter default values for fall and spring semesters</p>

        <p class="MAVselect">Minimum number of credit hours:
        <select name="FSmin">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12" selected>12</option>
            <option value="13">13</option>
            <option value="14">14</option>
            <option value="15">15</option>
            <option value="16">16</option>
            <option value="17">17</option>
            <option value="18">18</option>
        </select>
        </p>

        <p class="MAVselect">Maximum number of credit hours:
        <select name="FSmax">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7"">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
            <option value="13">13</option>
            <option value="14">14</option>
            <option value="15">15</option>
            <option value="16">16</option>
            <option value="17">17</option>
            <option value="18" selected>18</option>
        </select>
        </p>

        <br>

        <p name ="summer-credits" class="MAVselect">Do you prefer to take summer classes in general?
            <input type="radio" name="summer-course" checked="checked" value="True" onclick="showSummerInfo()"> Yes
            <input type="radio" name="summer-course" value="False" onclick="hideSummerInfo()"> No
        </p>

        <div id="summer-info">

            <p class="MAVselect">Minimum number of credit hours:
            <select name="Summin">
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3" selected>3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
                <option value="13">13</option>
                <option value="14">14</option>
                <option value="15">15</option>
                <option value="16">16</option>
                <option value="17">17</option>
                <option value="18">18</option>
            </select>
            </p>

            <p  class="MAVselect">Maximum number of credit hours:
            <select name="Summax">
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6" selected>6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
                <option value="13">13</option>
                <option value="14">14</option>
                <option value="15">15</option>
                <option value="16">16</option>
                <option value="17">17</option>
                <option value="18">18</option>
            </select>
            </p>

        </div>

        <button type="submit" name="submit" value="submit" class="MAVbutton">submit</button>
    </div>

</form>
<br>

{% endblock %}

mavAgenda/landing/templates/landing/login.html
{% extends 'landing/base.html' %}
{% block content %}
<br>
<div id="register" class="row">
    <form class="email" id = "email" method="post">
        {% csrf_token %}

        <p class="errormessage" id="errormessage">{{message}}</p>
        <p id="emailbox" name="emailbox" class="submissionBox">Email:<input id="email-input" name="email-input"
               minlength="1" required
               placeholder="Email" />
        </p>

        {{emailForm.email}}
            <br>
            <input type="submit" value="login" class="MAVbutton"/>
        </p>
    </form>
    <br>
    <br>
    <br>
    <br>
    <p style="text-align: center">Don't have an account yet?</p>
    <br>
    <form class="joinnow" id = "joinnow" action="{% url 'landing:createuser' %}" method="get">
        {% csrf_token %}

        <input type="submit" value="register" class="MAVbutton"/>
    </form>
</div>

{% endblock %}

mavAgenda/landing/templates/landing/schedule.html
{% extends 'landing/base.html' %}
{% block content %}
<br>

<h3>Your Generated Schedule</h3>
<br>
{% for semester in schedule %}
    <!-- this "box" div is for each semester -->
    <div class = "box" >
        <!-- print the Spring/Summer/Fall Semester and Year -->
        <p class="boxheader">{{ semester.0 }} {{ semester.1 }}</p>
        {% for course in semester.2 %}
        <p>{{ course }} >>> {{ course.credits }} credits </p>
        {% endfor %}
    </div>
<br>
{% endfor %}
<br>
<form class="joinnow" id = "joinnow" action="{% url 'landing:selectcourses' pk=userID %}" method="get">

    <p align="center">
    <input name="updateCourses" type="submit" value="update courses completed" class="MAVbutton"/>
    </p>

</form>


<!-- CANDIDATE FOR FUTURE DEVELOPMENT -->
<!--
    Right now, our views are set up so that on the createuser page, there can't be a userID...
    We should either find a way to allow a userID so that the user could change their major, or
    provide a separate page for update to this information (in addition to things like
    maximum number of credits desired in a semester, fulltime/parttime, and summer class options)
-->
<!--
<form class="joinnow" id = "joinnow" action="{% url 'landing:createuser' %}" method="get">

    <p align="center">
    <input type="submit" value="update major" class="MAVbutton"  style="padding: 8px 8px"/>
    </p>

</form>
-->

{% endblock %}